#pragma once


#define r_STR_MACRODEFINE "define"
#define r_STR_MACROIFDEF "ifdef"
#define r_STR_MACROIFNDEF "ifndef"
#define r_STR_MACROINCLUDE "include"
#define r_STR_MACROIF "if"
#define r_STR_MACROENDIF "endif"
#define r_STR_MACROELSE "else"
#define r_STR_MACROELIF "elif"
#define r_STR_WHILE "while"
#define r_STR_ELSE "else"
#define r_STR_FOR "for"
#define r_STR_IF "if"
#define r_STR_SWITCH "switch"
#define r_STR_CASE "case"
#define r_STR_DEFAULT "default"
#define r_STR_GOTO "goto"
#define r_STR_DO "do"
#define r_STR_SIZEOF "sizeof"
#define r_STR_EXTERN "extern"
#define r_STR_REGISTER "register"
#define r_STR_AUTO "auto"
#define r_STR_STATIC "static"
#define r_STR_TYPEDEF "typedef"
#define r_STR_STRUCT "struct"
#define r_STR_UNION "union"
#define r_STR_ENUM "enum"
#define r_STR_RETURN "return"
#define r_STR_CONTINUE "continue"
#define r_STR_BREAK "break"
#define r_STR_CONST "const"
#define r_STR_VOLATILE "volatile"